#!/bin/bash

cp -f "$(dirname $0)/emmc-install" /usr/bin/emmc-install

chmod +x /usr/bin/emmc-install

cat << EOF > /etc/systemd/system/emmc-install.service
[Unit]
Description=Install systemd to emmc
ConditionFileIsExecutable=/usr/bin/emmc-install
After=local-fs.target

[Service]
Type=oneshot
StandardOutput=journal+console
ExecStart=/usr/bin/emmc-install
RemainAfterExit=true


[Install]
WantedBy=multi-user.target
EOF

ln -s /etc/systemd/system/emmc-install.service /etc/systemd/system/multi-user.target.wants/

rm -f /root/.not_logged_in_yet
rm -rf /etc/systemd/system/getty@.service.d
rm -rf /etc/systemd/system/serial-getty@.service.d