#!/bin/bash


# Check if current system is booted from eMMC

root_devname="$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print substr($3, 1, length($3)-2)}')"
if lsblk -l | grep -E "^${root_devname}boot0" >/dev/null; then
    echo "Current system is already installed to eMMC!"
    rm $0
    exit 0
fi

source /etc/ophub-release
source /boot/ophub-release || true

if [[ -z "$MODEL_ID" ]] || [[ ! "$MODEL_ID" -eq "$MODEL_ID" ]]; then
    for i in {1..10} ; do
        echo "Failed to identify the model, please manually execute \"armbian-install\" "
    done
    exit 1
fi
systemctl stop bxc-node
rm -f /root/.bcode.txt

printf "$MODEL_ID\n2\n\n" | armbian-install

mount ${root_devname}p2 /mnt
rm -vf /mnt/usr/bin/emmc-install
if [[ -n "$MAC_PREFIX" ]] ; then
    MAC_PREFIX_=${MAC_PREFIX//:/""}
    MAC_PREFIX_CNT=$((${#MAC_PREFIX_} / 2 ))

    MAC=$MAC_PREFIX:$(hexdump -n${MAC_PREFIX_CNT} -e "$MAC_PREFIX_CNT/1 \":%02x\"" /dev/urandom | awk ' { sub(/^:../, "02"); print } ')

    printf "allow-hotplug eth0
iface eth0 inet dhcp
hwaddress ${MAC}\n" > /mnt/etc/network/interfaces.d/eth0
fi
umount /mnt

sync;sync; echo 3 > /proc/sys/vm/drop_caches
sleep 20
poweroff
